### ISSUE TITLE
Games

### ISSUE THREAD

**Issue by kolyaventuri** [alexcutschall/battleshift#10]

**Comment by jmejia** [comment]
@kolyaventuri This was started 4 days ago. Any progress made?

**Comment by kolyaventuri** [comment]
@jmejia This was completed by @alexcutschall on a different branch. We shifted around priorities/responsibilities, and I must have just never cleaned this up or closed this. We need to be better about consistently checking/updating waffle.

**Comment by jmejia** [comment]
@kolyaventuri 👍
