### ISSUE TITLE
Shot endpoint - Hit/Miss

### ISSUE THREAD

**Issue by alexcutschall** [alexcutschall/battleshift#6]
Send a target coordinate to fire upon the opponents board. Sender is determined by the API key that is sent over. Should only allow players who are part of this game. Should not allow a user to fire when it is not their turn.

**Comment by jmejia** [comment]
@alexcutschall What's the status on this story? I see you started it but I don't see anything in the codebase that indicates this has been worked on.

**Comment by jmejia** [comment]
@alexcutschall This should also probably be multiple stories.

**Comment by kolyaventuri** [comment]
@jmejia @alexcutschall I will reassign this to me and split it into multiple stories. See #20 for the hit/miss logic.
